version: "3"
services:
  ovms-server:
    build:
      context: .
      dockerfile: server.Dockerfile
    image: ovms-server:0.0.2-amd64
    restart: always
    ports:
      - "9010:9010"
    entrypoint: "sh -c"
    command: >
      "/ovms/bin/ovms
      --model_path /models/yolov3
      --model_name yolov3 --port 9010"
  ovms-app:
    build:
      context: .
      dockerfile: app.Dockerfile
    image: ovms-app:0.0.2-amd64
    restart: always
    environment:
      PYTHONUNBUFFERED: "1"
    ports:
      - "5010:5010"
      - "44000:44000"
      - "8888:8888"
    depends_on:
      - "ovms-server"
